### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Hojat1995** [Sync-/powermetering#1]
hi,I am hojat and thank you for this project, i am working on ade9000 by arduino , i saw you have worked on stm so i downloaded that , but when i open eagle files that give me one error:

Loading C:/Users/hh/Downloads/powermetering-master/powermetering-master/stm32.sch ...

Error:

**line 1, column 1: Start tag expected.**

can you help me ,why?

**Comment by luksal** [comment]
It's made with KiCAD not eagle

**Comment by Sync-** [comment]
Luksal is correct, this project is designed in KiCAD.

**Comment by Hojat1995** [comment]
oops, THANKS.I didn't know this software, I will download it and test it,THANKS again.    On Tuesday, June 4, 2019, 8:36:19 PM GMT+4:30, Sync- <notifications@github.com> wrote:  
 
 
Closed #1.

**Comment by Hojat1995** [comment]
My win recognize under software . Can you tell me which software do you use?I use altium and kail ,eagle and codvision and atmel are install.
    On Tuesday, June 4, 2019, 8:36:18 PM GMT+4:30, Sync- <notifications@github.com> wrote:  
 
 
Luksal is correct, this project is designed in KiCAD.
