### ISSUE TITLE
GPN19 slides

### ISSUE THREAD

**Issue by luksal** [Sync-/powermetering#2]
I saw that there was a talk about this powermeter project at the GPN19, which is unfortunately not available as a recording. Is it possible to get the slides and other informations about this?

**Comment by Sync-** [comment]
The slides are here: https://pretalx.entropia.de/gpn19/talk/TFASVY/
However there is not much information beyond what you can find in the git repo.

**Comment by luksal** [comment]
Clicking on the slides link gives a 404

**Comment by Sync-** [comment]
Huh, that seems like a problem on their end, I'll see what I can do.
